#ifndef COLOR_H
#define COLOR_H

#include "./objects_code.h"

typedef enum {
  TETRAMINO_COLOR_RED = OBJECT_CODE_TETRAMINO_I,
  TETRAMINO_COLOR_MAGNETA = OBJECT_CODE_TETRAMINO_O,
  TETRAMINO_COLOR_BLUE = OBJECT_CODE_TETRAMINO_T,
  TETRAMINO_COLOR_GREEN = OBJECT_CODE_TETRAMINO_S,
  TETRAMINO_COLOR_DARK_MAGNETA = OBJECT_CODE_TETRAMINO_Z,
  TETRAMINO_COLOR_DARK_YELLOW = OBJECT_CODE_TETRAMINO_J,
  TETRAMINO_COLOR_YELLOW = OBJECT_CODE_TETRAMINO_L,
} Color_t;

#endif  // COLOR_H
