#ifndef OBJECTS_CODE
#define OBJECTS_CODE

typedef enum {
  OBJECT_CODE_AIR = -2,
  OBJECT_CODE_WALL = -1,

  OBJECT_CODE_TETRAMINO_I = 1,
  OBJECT_CODE_TETRAMINO_O = 2,
  OBJECT_CODE_TETRAMINO_T = 3,
  OBJECT_CODE_TETRAMINO_S = 4,
  OBJECT_CODE_TETRAMINO_Z = 5,
  OBJECT_CODE_TETRAMINO_J = 6,
  OBJECT_CODE_TETRAMINO_L = 7,
} ObjectCode_t;

typedef enum {
  PAUSE_MODE_Pause = 1,
  PAUSE_MODE_CONTINUE = 2,
  PAUSE_MODE_START = 3,
  PAUSE_MODE_GAME_OVER = 4,
  PAUSE_MODE_EXIT = 5,
  PAUSE_MODE_WIN = 6
} PauseMode_t;

#endif  // OBJECTS_CODE
