#ifndef TETRAMINO_H
#define TETRAMINO_H

#include <stdlib.h>

#define TETRAMINO_WIDTH 4
#define TETRAMINO_HEIGHT 4

typedef enum {
  OBJECT_CODE_AIR = -2,
  OBJECT_CODE_WALL = -1,

  OBJECT_CODE_TETRAMINO_I = 1,
  OBJECT_CODE_TETRAMINO_O = 2,
  OBJECT_CODE_TETRAMINO_T = 3,
  OBJECT_CODE_TETRAMINO_S = 4,
  OBJECT_CODE_TETRAMINO_Z = 5,
  OBJECT_CODE_TETRAMINO_J = 6,
  OBJECT_CODE_TETRAMINO_L = 7,
} ObjectCode_t;

typedef enum {
  TETRAMINO_COLOR_RED = OBJECT_CODE_TETRAMINO_I,
  TETRAMINO_COLOR_MAGNETA = OBJECT_CODE_TETRAMINO_O,
  TETRAMINO_COLOR_BLUE = OBJECT_CODE_TETRAMINO_T,
  TETRAMINO_COLOR_GREEN = OBJECT_CODE_TETRAMINO_S,
  TETRAMINO_COLOR_DARK_MAGNETA = OBJECT_CODE_TETRAMINO_Z,
  TETRAMINO_COLOR_DARK_YELLOW = OBJECT_CODE_TETRAMINO_J,
  TETRAMINO_COLOR_YELLOW = OBJECT_CODE_TETRAMINO_L,
} Color;

typedef struct {
  int x;
  int y;
  Color color;
  int brick[TETRAMINO_HEIGHT][TETRAMINO_WIDTH];
} Tetramino_t;

#endif  // TETRAMINO_H
