#ifndef DESKTOP_WINDOW_DEFINES_H
#define DESKTOP_WINDOW_DEFINES_H

namespace s21 {

// Window dimensions
#define WINDOW_WIDTH 600
#define WINDOW_HEIGHT 900

// Layout margins
#define LAYOUT_MARGIN 0
#define RIGHT_PANEL_SPACING 15
#define RIGHT_PANEL_TOP_MARGIN 10
#define RIGHT_PANEL_RIGHT_MARGIN 10
#define RIGHT_PANEL_LEFT_MARGIN 1
#define RIGHT_PANEL_BOTTOM_MARGIN 1

// Stretch factors
#define LEFT_STRETCH_FACTOR 2
#define RIGHT_STRETCH_FACTOR 1

// Widget sizes
#define NEXT_FIGURE_SIZE 120

// Colors
#define BACKGROUND_COLOR "#2E2E2E"
#define INFO_BLOCK_COLOR "#252525"
#define NEXT_FIGURE_BG_COLOR "#222222"
#define BUTTON_NORMAL_COLOR "#444444"
#define BUTTON_HOVER_COLOR "#555555"
#define BUTTON_PRESSED_COLOR "#333333"
#define BORDER_COLOR "#666666"
#define TITLE_COLOR "#888888"
#define VALUE_COLOR "#FFFFFF"
#define HELP_TEXT_COLOR "#CCCCCC"

// Styling values
#define BUTTON_PADDING 15
#define BUTTON_FONT_SIZE 18
#define BORDER_RADIUS 12
#define BORDER_WIDTH 1
#define FRAME_PADDING 3
#define SMALL_PADDING 2
#define MINIMAL_PADDING 1
#define TITLE_FONT_SIZE 16
#define VALUE_FONT_SIZE 28
#define HELP_FONT_SIZE 16
#define HELP_LINE_HEIGHT 1.5

// Other constants
#define PANEL_COUNT 4

}  // namespace s21

#endif  // DESKTOP_WINDOW_DEFINES_H
