#ifndef OBJECTS_CODE_H
#define OBJECTS_CODE_H

typedef enum {
  OBJECT_CODE_AIR = -2,
  OBJECT_CODE_WALL = -1,
  OBJECT_CODE_TETRAMINO_I = 0,
  OBJECT_CODE_TETRAMINO_O,
  OBJECT_CODE_TETRAMINO_T,
  OBJECT_CODE_TETRAMINO_S,
  OBJECT_CODE_TETRAMINO_Z,
  OBJECT_CODE_TETRAMINO_J,
  OBJECT_CODE_TETRAMINO_L,

  OBJECT_CODE_SNAKE = 10,
  OBJECT_CODE_APPLE,
} ObjectCode;

typedef enum {
  PAUSE_MODE_PAUSE = 0,
  PAUSE_MODE_START,
  PAUSE_MODE_GAME_OVER
} PauseMode;

#endif  // OBJECTS_CODE_H
